# Generated by Django 3.0.5 on 2020-04-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mne', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('lob', models.CharField(choices=[('CoreBanking', 'CoreBanking'), ('WebPayment', 'WebPayment'), ('ATH', 'ATH')], max_length=200, null=True)),
                ('critic', models.CharField(choices=[('HIGH', 'HIGH'), ('Normal', 'Normal')], max_length=200, null=True)),
                ('Patch_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=200, null=True)),
            ],
        ),
    ]
