# Generated by Django 3.0.5 on 2020-04-16 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('os', models.CharField(choices=[('UNIX', 'UNIX'), ('Windows', 'Windows')], max_length=200, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contact.Apps')),
            ],
        ),
    ]
