# Generated by Django 3.0.5 on 2020-04-16 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0002_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='F5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f5_url', models.URLField()),
                ('f5_partitions', models.TextField()),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contact.Apps')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=100)),
                ('contacto_val', models.CharField(max_length=100)),
                ('contacto_oncall', models.CharField(max_length=100)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contact.Apps')),
            ],
        ),
    ]
